# Generated by Django 5.0.4 on 2024-04-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='password',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='username',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='id',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='password',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='climber',
            name='username',
        ),
        migrations.AddField(
            model_name='centre',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climber',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
