# Generated by Django 5.0.4 on 2024-04-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_centre_user_centre_owner_alter_climber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='image',
            field=models.ImageField(blank=True, upload_to='centres'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='setters',
            field=models.ManyToManyField(blank=True, related_name='employers', to='tracker.climber'),
        ),
        migrations.AlterField(
            model_name='climber',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='tracker.centre'),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='centre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='tracker.centre'),
        ),
    ]
