# Generated by Django 5.0.4 on 2024-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_centre_image_alter_centre_setters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='name',
            field=models.TextField(default='The Reach', max_length=100),
            preserve_default=False,
        ),
    ]
