# Generated by Django 5.0.4 on 2024-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_centre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='name',
            field=models.TextField(default='all', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centre',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/centres'),
        ),
    ]
