# Generated by Django 5.0.4 on 2024-05-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_wall_name_alter_centre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tracker.route'),
            preserve_default=False,
        ),
    ]
