# Generated by Django 5.0.4 on 2024-10-05 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='climbers',
            field=models.ManyToManyField(related_name='climbed_grades', to='tracker.climber'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tracker.climber')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tracker.grade')),
            ],
        ),
    ]
