# Generated by Django 5.0.4 on 2024-10-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_grade_climbers_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
