# Generated by Django 5.0.4 on 2024-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='My first review!'),
            preserve_default=False,
        ),
    ]
